name: Build image

on:
  workflow_dispatch:
    branches:
      - master
    paths:
      - 'Dockerfile'

env:
  IMAGE_NAME: ps4-pkg-sender

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4

      # Install and set up Docker Buildx for multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      # Build and push the image for multiple architectures (amd64, arm64)
      - name: Build and push image
        run: |
          docker buildx create --use
          docker buildx build . --no-cache \
            --file Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest \
            --push
